In [22]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score
import numpy as np



iris = datasets.load_iris()
X = iris.data[:, [2, 3]]
y = iris.target

print("classes in iris ds: {}".format(len(np.unique(y))))

# split model into traing and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
ss = StandardScaler()
ss.fit(X_train)
X_train_scaled = ss.transform(X_train)
X_test_scaled = ss.transform(X_test)

ppn = Perceptron(n_iter=40, eta0=0.1, random_state=0)
ppn.fit(X_train_scaled, y_train)
y_predict = ppn.predict(X_test_scaled)

print('Acc of perceptron is: {}'.format(accuracy_score(y_test, y_predict)))

classes in iris ds: 3
Acc of perceptron is: 0.911111111111


In [29]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=1000.0, random_state=0)
lr.fit(X_train_scaled, y_train)
y_predict = lr.predict_proba(X_test_scaled)

print('Logistic regression probabilities for every test sample: \n{}'.format(y_predict))

Logistic regression probabilities for every test sample: 
[[  2.05743774e-11   6.31620264e-02   9.36837974e-01]
 [  6.08753106e-04   9.99285569e-01   1.05678028e-04]
 [  8.16962653e-01   1.83037347e-01   6.48299403e-14]
 [  1.60866539e-11   4.14084479e-01   5.85915521e-01]
 [  8.00231776e-01   1.99768224e-01   1.07576258e-13]
 [  2.03283749e-13   1.38353563e-01   8.61646437e-01]
 [  8.64726967e-01   1.35273033e-01   9.27705289e-14]
 [  4.92680691e-07   7.61844645e-01   2.38154862e-01]
 [  6.63326495e-07   8.43292211e-01   1.56707126e-01]
 [  8.06447009e-05   9.97737477e-01   2.18187798e-03]
 [  9.03984802e-09   4.62107297e-01   5.37892694e-01]
 [  1.54213753e-06   8.75626483e-01   1.24371975e-01]
 [  5.21240195e-06   9.81860065e-01   1.81347231e-02]
 [  8.78337572e-07   8.24894420e-01   1.75104701e-01]
 [  1.13609831e-06   8.90634747e-01   1.09364117e-01]
 [  7.63277074e-01   2.36722926e-01   4.48028267e-14]
 [  1.54213753e-06   8.75626483e-01   1.24371975e-01]
 [  2.17883410e-05   9.9

In [33]:
from sklearn.svm import SVC

svm = SVC(kernel='linear', C=1.0, random_state=0)
svm.fit(X_train_scaled, y_train)
y_predict = svm.predict(X_test_scaled)

print('Acc of SVM is: {}'.format(accuracy_score(y_test, y_predict)))

Acc of SVM is: 0.977777777778


In [ ]:
# trick to get model trained on huge datasets: use SGD
from sklearn.linear_model import SGDClassifier

ppn = SGDClassifier(loss='perceptron')
lr = SGDClassifier(loss='log')
svm = SGDClassifier(loss='hinge')